on:
  push:
    tags:
      - 'v*' # 触发条件为：推送tag，且tag开头是v，例如v1.0.0

permissions:
  contents: write # 授予actions发布release的权限

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # 初始化node和pnpm环境
      - uses: pnpm/action-setup@v2 
        with:
          version: 6.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      # 安装依赖
      - run: npm install
      # 编译脚本
      - run: npm run build
      # 发布release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/pornHelper.user.js

